default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: fran        # Aquí coloca el nombre de tu usuario PostgreSQL
  password: paquirri    # Aquí coloca la contraseña de tu usuario PostgreSQL

development:
  <<: *default
  database: GestonEventos_development  # Aquí va el nombre de la base de datos para desarrollo

test:
  <<: *default
  database: GestonEventos_test  # Aquí va el nombre de la base de datos para pruebas

production:
  <<: *default
  database: GestonEventos_production  # Aquí va el nombre de la base de datos para producción
  username: fran
  password: paquirri  # Usa una variable de entorno para la contraseña
